language: node_js
sudo: required
node_js:
- '8'
before_install:
- pwd
- ls -lsFa
- touch ~/.ssh/id_rsa
- ls -lsF ~/.ssh
- openssl aes-256-cbc -K $encrypted_aa2043a425e0_key -iv $encrypted_aa2043a425e0_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "HOST 123.57.157.213\nport 58628\nStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install -g pm2
- npm install
script:
- npm run test
env:
- DB=mongodb
after_success:
- ssh root@123.57.157.213 '/data/run.sh'
